export const CART_APPEND_ITEM = "CART_APPEND_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

export const CART_REQUEST_SUCCESS = "CART_ITEMS_SUCCESS";
export const REMOVE_ITEMS_SUCCESS =  "REMOVE_ITEMS_SUCCESS";