//item list
export const ITEM_LIST_REQUEST = "ITEM_LIST_REQUEST";
export const ITEM_LIST_SUCCESS = "ITEM_LIST_SUCCESS";
export const ITEM_LIST_FAIL = "ITEM_LIST_FAIL";

//item details
export const ITEM_DETAIL_REQUEST = "ITEM_DETAIL_REQUEST";
export const ITEM_DETAIL_SUCESS = "ITEM_DETAIL_SUCCESS";
export const ITEM_DETAIL_FAIL = "ITEM_DETAIL_FAIL";